#! validate-crd: deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
#! parse-kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: federation.v0.0.5
  namespace: placeholder
  annotations:
    categories: "OpenShift Optional, Integration & Delivery"
    description: "Kubernetes Federation namespace-scoped installation"
spec:
  displayName: Federation
  description: |
    This deploys Federation in a namespace-scoped configuration. After
    installation, you must enable the API types you want Federation to manage
    using `kubefed2 enable`.

    Note, you must enable federation support for namespaces in this
    configuration before other types will work. Use `kubefed2 enable namespaces`.
  version: 0.0.5
  maturity: alpha
  provider:
    name: Red Hat
  labels:
    alm-owner-federation: federation
    alm-status-descriptors: federation.v0.0.5
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: federation-controller-manager
        rules:
        - apiGroups:
          - clusterregistry.k8s.io
          resources:
          - clusters
          verbs:
          - "*"
        - apiGroups:
          - core.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - primitives.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - multiclusterdns.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - scheduling.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
      # TODO(font): use statefulset
      deployments:
      - name: federation-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: federation-controller-manager
          template:
            metadata:
              labels:
                app: federation-controller-manager
            spec:
              containers:
                - name: controller-manager
                  image: quay.io/pmorie/origin-federation-controller:v4.0.0
                  resources:
                    limits:
                      cpu: 100m
                      memory: 128Mi
                    requests:
                      cpu: 100m
                      memory: 64Mi
                  command:
                    - /root/controller-manager
                  args:
                    - --federation-namespace=$(FEDERATION_NAMESPACE)
                    - --install-crds=false
                    - --limited-scope=true
                    - --registry-namespace=$(CLUSTER_REGISTRY_NAMESPACE)
                    - -v=5
                    - --logtostderr
                  imagePullPolicy: Always
                  env:
                  - name: FEDERATION_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: CLUSTER_REGISTRY_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: federation-controller-manager
              serviceAccount: federation-controller-manager
  customresourcedefinitions:
    owned:
      - description: Represents an instance of a Cluster Registry
        displayName: Cluster Registry Application
        kind: Cluster
        name: clusters.clusterregistry.k8s.io
        version: v1alpha1
      - description: Represents a Domain name and nameserver for use with multicluster DNS.
        displayName: Domain
        kind: Domain
        name: domains.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedCluster resource
        displayName: FederatedCluster Resource
        kind: FederatedCluster
        name: federatedclusters.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederationV2 sync controller
        displayName: FederationV2 Push Reconciler Application
        kind: FederatedTypeConfig
        name: federatedtypeconfigs.core.federation.k8s.io
        version: v1alpha1
      - description: Represents the status of a FederatedService
        displayName: Federated service status
        kind: FederatedServiceStatus
        name: federatedservicestatuses.core.federation.k8s.io
        version: v1alpha1        
      - description: Represents an instance of a PropagatedVersion resource
        displayName: PropagatedVersion Resource
        kind: PropagatedVersion
        name: propagatedversions.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a DNSEndpoint resource
        displayName: DNSEndpoint Resource
        kind: DNSEndpoint
        name: dnsendpoints.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a MultiClusterIngressDNSRecord resource
        displayName: MultiClusterIngressDNSRecord Resource
        kind: IngressDNSRecord
        name: ingressdnsrecords.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a MultiClusterServiceDNSRecord resource
        displayName: MultiClusterServiceDNSRecord Resource
        kind: ServiceDNSRecord
        name: servicednsrecords.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a ReplicaSchedulingPreference resource
        displayName: ReplicaSchedulingPreference Resource
        kind: ReplicaSchedulingPreference
        name: replicaschedulingpreferences.scheduling.federation.k8s.io
        version: v1alpha1
